services:
  app:
    build: .
    ports:
      - "5173:5173"
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_PUBLISHABLE_KEY: ${VITE_SUPABASE_PUBLISHABLE_KEY}
      VITE_SHOW_THINKING: ${VITE_SHOW_THINKING:-false}
    env_file:
      - .env
